# Form implementation generated from reading ui file 'admin_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminPreferences(object):
    def setupUi(self, AdminPreferences):
        AdminPreferences.setObjectName("AdminPreferences")
        AdminPreferences.resize(620, 620)
        AdminPreferences.setMinimumSize(QtCore.QSize(520, 560))
        AdminPreferences.setStyleSheet("QWidget#AdminPreferences {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eef1f5, stop:0.5 #dde3ea, stop:1 #c9d1da);\n"
"}\n"
"\n"
"/* ---------- Logo ---------- */\n"
"QLabel#lblLogo {\n"
"    font-size: 36px;\n"
"    font-weight: 800;\n"
"    color: #37474f;\n"
"    letter-spacing: 4px;\n"
"}\n"
"\n"
"QLabel#lblLogoAccent {\n"
"    color: #e53935;\n"
"    font-weight: 800;\n"
"    font-size: 36px;\n"
"    letter-spacing: 4px;\n"
"}\n"
"\n"
"/* ---------- Red title bar ---------- */\n"
"QFrame#frmTitle {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #e53935, stop:1 #ff5252);\n"
"    border-radius: 6px;\n"
"    min-height: 38px;\n"
"    max-height: 38px;\n"
"}\n"
"\n"
"QLabel#lblTitle {\n"
"    color: #ffffff;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;\n"
"}\n"
"\n"
"/* ---------- Main card ---------- */\n"
"QFrame#frmMenu {\n"
"    background-color: rgba(255, 255, 255, 0.55);\n"
"    border: 1px solid rgba(255, 255, 255, 0.85);\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"/* ---------- Buttons ---------- */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ffffff, stop:1 #e6e9ee);\n"
"    color: #263238;\n"
"    border: 1px solid #b0bec5;\n"
"    border-radius: 8px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    padding: 12px 16px;\n"
"    min-height: 42px;\n"
"    text-align: center;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #e3f2fd, stop:1 #bbdefb);\n"
"    border: 1px solid #64b5f6;\n"
"    color: #0d47a1;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #bbdefb, stop:1 #90caf9);\n"
"}\n"
"QPushButton:focus {\n"
"    border: 2px solid #42a5f5;\n"
"}\n"
"\n"
"/* ---------- Admin (highlighted) ---------- */\n"
"QPushButton#btnAdmin {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ef5350, stop:1 #e53935);\n"
"    color: #ffffff;\n"
"    border: 1px solid #c62828;\n"
"}\n"
"QPushButton#btnAdmin:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #ff6659, stop:1 #d32f2f);\n"
"}\n"
"QPushButton#btnAdmin:pressed {\n"
"    background: #c62828;\n"
"}\n"
"\n"
"/* ---------- Exit button ---------- */\n"
"QPushButton#btnExit {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #607d8b, stop:1 #455a64);\n"
"    color: #ffffff;\n"
"    border: 1px solid #37474f;\n"
"}\n"
"QPushButton#btnExit:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #78909c, stop:1 #546e7a);\n"
"}")
        self.rootLayout = QtWidgets.QVBoxLayout(AdminPreferences)
        self.rootLayout.setContentsMargins(30, 25, 30, 25)
        self.rootLayout.setSpacing(14)
        self.rootLayout.setObjectName("rootLayout")
        self.rowLogo = QtWidgets.QHBoxLayout()
        self.rowLogo.setSpacing(12)
        self.rowLogo.setObjectName("rowLogo")
        self.lblAvatar = QtWidgets.QLabel(parent=AdminPreferences)
        self.lblAvatar.setMinimumSize(QtCore.QSize(70, 70))
        self.lblAvatar.setMaximumSize(QtCore.QSize(70, 70))
        self.lblAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAvatar.setStyleSheet("font-size: 52px; color: #e53935;")
        self.lblAvatar.setObjectName("lblAvatar")
        self.rowLogo.addWidget(self.lblAvatar)
        self.lblLogoText = QtWidgets.QLabel(parent=AdminPreferences)
        self.lblLogoText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblLogoText.setObjectName("lblLogoText")
        self.rowLogo.addWidget(self.lblLogoText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowLogo.addItem(spacerItem)
        self.rootLayout.addLayout(self.rowLogo)
        self.frmTitle = QtWidgets.QFrame(parent=AdminPreferences)
        self.frmTitle.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmTitle.setObjectName("frmTitle")
        self.titleLayout = QtWidgets.QHBoxLayout(self.frmTitle)
        self.titleLayout.setContentsMargins(15, 0, 15, 0)
        self.titleLayout.setObjectName("titleLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.frmTitle)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.titleLayout.addWidget(self.lblTitle)
        self.rootLayout.addWidget(self.frmTitle)
        self.frmMenu = QtWidgets.QFrame(parent=AdminPreferences)
        self.frmMenu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frmMenu.setObjectName("frmMenu")
        self.menuGrid = QtWidgets.QGridLayout(self.frmMenu)
        self.menuGrid.setContentsMargins(40, 35, 40, 35)
        self.menuGrid.setSpacing(22)
        self.menuGrid.setObjectName("menuGrid")
        self.btnApplications = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnApplications.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnApplications.setObjectName("btnApplications")
        self.menuGrid.addWidget(self.btnApplications, 0, 0, 1, 1)
        self.btnMentorInterview = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnMentorInterview.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMentorInterview.setObjectName("btnMentorInterview")
        self.menuGrid.addWidget(self.btnMentorInterview, 0, 1, 1, 1)
        self.btnInterviews = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnInterviews.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnInterviews.setObjectName("btnInterviews")
        self.menuGrid.addWidget(self.btnInterviews, 1, 0, 1, 1)
        self.btnAdmin = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnAdmin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAdmin.setObjectName("btnAdmin")
        self.menuGrid.addWidget(self.btnAdmin, 1, 1, 1, 1)
        self.btnMainMenu = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnMainMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMainMenu.setObjectName("btnMainMenu")
        self.menuGrid.addWidget(self.btnMainMenu, 2, 0, 1, 1)
        self.btnExit = QtWidgets.QPushButton(parent=self.frmMenu)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnExit.setObjectName("btnExit")
        self.menuGrid.addWidget(self.btnExit, 2, 1, 1, 1)
        self.rootLayout.addWidget(self.frmMenu)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.rootLayout.addItem(spacerItem1)

        self.retranslateUi(AdminPreferences)
        QtCore.QMetaObject.connectSlotsByName(AdminPreferences)

    def retranslateUi(self, AdminPreferences):
        _translate = QtCore.QCoreApplication.translate
        AdminPreferences.setWindowTitle(_translate("AdminPreferences", "Admin Preference Menu"))
        self.lblAvatar.setText(_translate("AdminPreferences", "👤"))
        self.lblLogoText.setText(_translate("AdminPreferences", "<html><head/><body><p><span style=\"font-size:36pt; font-weight:800; color:#37474f; letter-spacing:4px;\">WER</span><span style=\"font-size:36pt; font-weight:800; color:#e53935; letter-spacing:4px;\">:</span><span style=\"font-size:36pt; font-weight:800; color:#37474f; letter-spacing:4px;\">HERE</span></p></body></html>"))
        self.lblTitle.setText(_translate("AdminPreferences", "CRM — Admin Preference Menu"))
        self.btnApplications.setText(_translate("AdminPreferences", "📄   Applications"))
        self.btnMentorInterview.setText(_translate("AdminPreferences", "🎓   Mentor Interview"))
        self.btnInterviews.setText(_translate("AdminPreferences", "📋   Interviews"))
        self.btnAdmin.setText(_translate("AdminPreferences", "🛡️   Admin Menu"))
        self.btnMainMenu.setText(_translate("AdminPreferences", "🏠   Main Menu"))
        self.btnExit.setText(_translate("AdminPreferences", "❌   Exit"))
