# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(440, 640)
        LoginWindow.setMinimumSize(QtCore.QSize(380, 560))
        LoginWindow.setStyleSheet("QWidget#LoginWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0f2027, stop:0.5 #203a43, stop:1 #2c5364);\n"
"}\n"
"\n"
"QFrame#frmCard {\n"
"    background-color: rgba(255, 255, 255, 0.06);\n"
"    border: 1px solid rgba(255, 255, 255, 0.12);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel#lblLogo {\n"
"    font-size: 30px;\n"
"    font-weight: 800;\n"
"    color: #ffffff;\n"
"    letter-spacing: 4px;\n"
"}\n"
"\n"
"QLabel#lblSubtitle {\n"
"    color: #b0bec5;\n"
"    font-size: 12px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLabel#lblField {\n"
"    color: #90a4ae;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.08);\n"
"    color: #ffffff;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 12px;\n"
"    padding: 10px 14px;\n"
"    font-size: 13px;\n"
"    min-height: 22px;\n"
"    selection-background-color: #26c6da;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgba(255, 255, 255, 0.12);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #26c6da;\n"
"    background-color: rgba(255, 255, 255, 0.14);\n"
"}\n"
"\n"
"QCheckBox#chkShow {\n"
"    color: #cfd8dc;\n"
"    font-size: 12px;\n"
"    spacing: 8px;\n"
"}\n"
"QCheckBox#chkShow::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #607d8b;\n"
"    background-color: transparent;\n"
"}\n"
"QCheckBox#chkShow::indicator:hover {\n"
"    border-color: #26c6da;\n"
"}\n"
"QCheckBox#chkShow::indicator:checked {\n"
"    background-color: #26c6da;\n"
"    border-color: #26c6da;\n"
"}\n"
"\n"
"QPushButton#btnLogin {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #00acc1, stop:1 #26c6da);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 12px;\n"
"    min-height: 40px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QPushButton#btnLogin:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #26c6da, stop:1 #4dd0e1);\n"
"}\n"
"QPushButton#btnLogin:pressed {\n"
"    background: #00838f;\n"
"}\n"
"\n"
"QPushButton#btnExit {\n"
"    background-color: transparent;\n"
"    color: #cfd8dc;\n"
"    border: 2px solid rgba(255, 255, 255, 0.2);\n"
"    border-radius: 12px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    min-height: 36px;\n"
"}\n"
"QPushButton#btnExit:hover {\n"
"    border-color: #ef5350;\n"
"    color: #ef5350;\n"
"}\n"
"\n"
"QLabel#lblError {\n"
"    color: #ff5252;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLabel#lblForgot {\n"
"    color: #90a4ae;\n"
"    font-size: 12px;\n"
"}\n"
"QLabel#lblForgot:hover {\n"
"    color: #26c6da;\n"
"}")
        self.rootLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.rootLayout.setContentsMargins(30, 30, 30, 30)
        self.rootLayout.setSpacing(0)
        self.rootLayout.setObjectName("rootLayout")
        self.frmCard = QtWidgets.QFrame(parent=LoginWindow)
        self.frmCard.setObjectName("frmCard")
        self.cardLayout = QtWidgets.QVBoxLayout(self.frmCard)
        self.cardLayout.setContentsMargins(36, 40, 36, 36)
        self.cardLayout.setSpacing(14)
        self.cardLayout.setObjectName("cardLayout")
        self.lblLogo = QtWidgets.QLabel(parent=self.frmCard)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.cardLayout.addWidget(self.lblLogo)
        self.lblSubtitle = QtWidgets.QLabel(parent=self.frmCard)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.cardLayout.addWidget(self.lblSubtitle)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cardLayout.addItem(spacerItem)
        self.lblUser = QtWidgets.QLabel(parent=self.frmCard)
        self.lblUser.setObjectName("lblUser")
        self.cardLayout.addWidget(self.lblUser)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frmCard)
        self.txtUsername.setObjectName("txtUsername")
        self.cardLayout.addWidget(self.txtUsername)
        self.lblPass = QtWidgets.QLabel(parent=self.frmCard)
        self.lblPass.setObjectName("lblPass")
        self.cardLayout.addWidget(self.lblPass)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frmCard)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.cardLayout.addWidget(self.txtPassword)
        self.rowShow = QtWidgets.QHBoxLayout()
        self.rowShow.setSpacing(0)
        self.rowShow.setObjectName("rowShow")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.rowShow.addItem(spacerItem1)
        self.chkShow = QtWidgets.QCheckBox(parent=self.frmCard)
        self.chkShow.setObjectName("chkShow")
        self.rowShow.addWidget(self.chkShow)
        self.cardLayout.addLayout(self.rowShow)
        self.lblError = QtWidgets.QLabel(parent=self.frmCard)
        self.lblError.setText("")
        self.lblError.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblError.setObjectName("lblError")
        self.cardLayout.addWidget(self.lblError)
        self.btnLogin = QtWidgets.QPushButton(parent=self.frmCard)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setObjectName("btnLogin")
        self.cardLayout.addWidget(self.btnLogin)
        self.btnExit = QtWidgets.QPushButton(parent=self.frmCard)
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnExit.setObjectName("btnExit")
        self.cardLayout.addWidget(self.btnExit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cardLayout.addItem(spacerItem2)
        self.lblForgot = QtWidgets.QLabel(parent=self.frmCard)
        self.lblForgot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblForgot.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.lblForgot.setObjectName("lblForgot")
        self.cardLayout.addWidget(self.lblForgot)
        self.rootLayout.addWidget(self.frmCard)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "CRM Login"))
        self.lblLogo.setText(_translate("LoginWindow", "WerHere"))
        self.lblSubtitle.setText(_translate("LoginWindow", "Customer Relationship Management"))
        self.lblUser.setText(_translate("LoginWindow", "USERNAME"))
        self.txtUsername.setPlaceholderText(_translate("LoginWindow", "Enter your username"))
        self.lblPass.setText(_translate("LoginWindow", "PASSWORD"))
        self.txtPassword.setPlaceholderText(_translate("LoginWindow", "Enter your password"))
        self.chkShow.setText(_translate("LoginWindow", "Show password"))
        self.btnLogin.setText(_translate("LoginWindow", "LOGIN"))
        self.btnExit.setText(_translate("LoginWindow", "EXIT"))
        self.lblForgot.setText(_translate("LoginWindow", "Forgot password?"))
